apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-calc-backend
spec:
  replicas: 1

  selector:
    matchLabels:
      app: go-calc-backend
      tier: backend
  template:
    metadata:
      labels:
        app: go-calc
    spec:
      containers:
      - name: go-calc-container
        image: magalhaesandre/rest-go-calc:latest
        ports:
        - containerPort: 8080