apiVersion: v1
kind: Service
metadata:
  name: go-calc-backend
  labels:
    app: go-calc
    tier: backend
  
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: go-calc
    tier: backend